"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['get_db_connection', 'insert_prescription_items']

# %% ../nbs/00_core.ipynb 3
import psycopg2
from psycopg2.extras import execute_batch
import pandas as pd
from typing import Optional, Dict, Any

# %% ../nbs/00_core.ipynb 4
def get_db_connection(
    dbname: str = "dosage_limits",
    user: str = "titan",
    password: str = "titan",
    host: str = "localhost",
    port: int = 5432
) -> psycopg2.extensions.connection:
    """Create and return a PostgreSQL database connection."""
    conn = psycopg2.connect(
        dbname=dbname,
        user=user,
        password=password,
        host=host,
        port=port
    )
    return conn

# %% ../nbs/00_core.ipynb 5
def insert_prescription_items(conn, items: list):
    """Insert prescription items into the database in batch."""
    cursor = conn.cursor()
    
    insert_query = """
        INSERT INTO prescription_items (
            prescription_id, pharmacy_name, pharmacy_code, prescription_date,
            patient_age, patient_gender, seq, code, drug, form, route,
            original_direction, additional_instructions, target_direction_manual,
            target_direction, dosage_field_seq, text, 
            strength, strength_max, strength_unit, 
            strength_numerator, strength_numerator_unit,
            strength_denominator, strength_denominator_unit, 
            dosage, dosage_max, dosage_unit, 
            frequency, frequency_max, 
            period, period_max, period_unit,
            duration, duration_max, duration_unit, 
            as_needed, indication,
            dosage_per_administration, dosage_per_administration_unit,
            dosage_numerator_per_administration, dosage_numerator_per_administration_unit,
            dosage_denominator_per_administration, dosage_denominator_per_administration_unit,
            dosage_per_period, dosage_per_period_unit,
            dosage_numerator_per_period, dosage_numerator_per_period_unit,
            dosage_denominator_per_period, dosage_denominator_per_period_unit,
            dosage_per_duration, dosage_per_duration_unit,
            dosage_numerator_per_duration, dosage_numerator_per_duration_unit,
            dosage_denominator_per_duration, dosage_denominator_per_duration_unit
        ) VALUES (
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s,
            %s, %s, %s, %s
        )
    """
    
    execute_batch(cursor, insert_query, items)
    conn.commit()
    cursor.close()

